### ISSUE TITLE
Issue with Angular version9:. this.tree.readText is not a function

### ISSUE THREAD

**Issue by Rebaiahmed** [alcfeoh/ng-weather#29] opened 2022-08-07 16:51 UTC
I'm using this project for getting a certificate purpose! but I faced a lot of issues blocked me to have stabe env and I canno't generate anymore any component or servcie using angular cli 
I downgarded my angular cli version but I faced a lot of issues .. please help
```
Your global Angular CLI version (9.1.13) is greater than your local
version (9.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
this.tree.readText is not a function
```

**Comment by alcfeoh** [comment] 2022-08-07 17:03
You can upgrade your fork to Angular 14. Using Angular 9 is not a requirement at all.

**Comment by Rebaiahmed** [comment] 2022-08-07 17:19
But trying to upgrade it will need some time, I downgrade my angular cli version to make this project compatible with my local env

**Comment by alcfeoh** [comment] 2022-08-16 19:17
The issue is now fixed.

**Closed** 2022-08-16 19:17 UTC
